FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN apk add --no-cache maven && mvn clean package -Dmaven.test.skip=true

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S kubinex && adduser -S kubinex -G kubinex
COPY --from=build /app/target/*.jar app.jar
RUN mkdir -p uploads logs && chown -R kubinex:kubinex /app
USER kubinex
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Xmx512m", "-Xms256m", "app.jar"]
